project:
  render:
    - "*.qmd"
    - "!TP_MAF_exemple.qmd"
  type: website

website:
  title: "Méthodes d'analyse factorielle"
  navbar:
    right:
      - href: index.qmd
        text: Home
    left:
      - icon: github
        href: https://github.com/MarieEtienne/MAF.git
        aria-label: GitHub
      - text: "References "
        menu:
          - text: Cours
            href: references_maf.qmd
          - text: Algèbre linéaire
            href: references_linear.qmd
      - text: "Cours"
        menu:
          - href: 01_intro.qmd
          - href: 01_inertie.qmd
          - href: 01_acp.qmd
          - href: 01_afm.qmd
          - href: 01_afc.qmd
          - href: 01_acm.qmd
          - href: 01_afd.qmd
          - href: 01_acp_manquantes.qmd

      - text: "TD/TP"
        menu:
          - text: TD1
            href: TP1.pdf
          - text: TD2
            href: TP2.qmd
          - text: TD3
            href: TP3.qmd
          - text: TD3 - script R
            href: TP3_scriptR.qmd
          - text: TD4
            href: TP4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
